import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'ko' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string, defaultText?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ko');

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'ko' ? 'en' : 'ko'));
  };

  const t = (key: string, defaultText?: string): string => {
    // If translations object lookup fails, fallback to defaultText or key
    const dictionary = translations[language] || translations['ko'];
    return dictionary[key] || defaultText || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const translations: Record<Language, Record<string, string>> = {
  ko: {
    // Header
    'header.orgName': '사단법인평화시민행동',
    'header.subOrgName': 'Peace Citizens Action Inc.',
    'nav.about': '소개',
    'nav.news': '소식 및 활동',
    'nav.sponsorship': '기억과 평화의 집 후원',
    'nav.archive': '아카이브',
    'header.donateBtn': '기억과 평화의 집 후원',
    'header.mobileDonateBtn': '기억과 평화의 집 후원 참여하기',

    // Hero
    'hero.badge': '윤금이 씨 사건 터 시민자산화사업 / 평화와 기억',
    'hero.titleLine1': '1992년 윤금이 씨 사건 현장을',
    'hero.titleLine2': '기억과 평화의 집으로',
    'hero.description': "1992년 동두천 보산동에서 발생한 윤금이 씨 사건의 아픈 역사가 남아있는 현장을 시민의 힘으로 매입합니다.\n감춰진 미군'위안부'의 역사를 기록하고 피해자들의 명예를 회복하며, 미래 세대를 위한 평화와 인권의 보금자리를 만들어갑니다.",
    'hero.btnDonate': '기억과 평화의 집 후원 참여하기',
    'hero.btnNews': '소식 & 활동 보기',
    'hero.trustBadge1': '지정기부금 단체 등록 추진 준비 중',
    'hero.trustBadge2': '투명한 재정 공시',
    'hero.campaignBadge': '건립 & 운영 캠페인',
    'hero.campaignTitle': '기억과 평화의 집 모금',
    'hero.campaignRate': '달성률',
    'hero.currentAmountLabel': '현재 모금액:',
    'hero.targetAmountLabel': '목표액:',
    'hero.donorsLabel': '함께한 시민 기부자',
    'hero.cheersLabel': '기부챌린지 응원한마디',
    'hero.unitPeople': '명',
    'hero.unitCount': '건',
    'hero.btnDonateCard': '지금 모금 동참하기',

    // About
    'about.sectionTag': '소개',
    'about.sectionTitle': '사단법인 평화시민행동 소개',
    'about.sectionSubtitle': '사단법인 평화시민행동은 분단의 상처를 치유하는 실천행동으로 평화인권의 가치를 실현합니다.',
    'about.headingTitle': '기억으로 일구는 평화의 미래',
    'about.foundingDate': '2026년 4월 27일 창립',
    'about.declarationHeader': '평화와 인권의 가치를 깊이 뿌리내립니다',
    'about.cardTitle': '시민들의 힘으로 세우는 평화와 인권의 공간',
    'about.cardText': "사단법인 평화시민행동은 2026년 4월 27일 창립하였습니다. 윤금이 씨 사건 터를 시민들의 힘으로 매입하여 '기억과 평화의 집'으로 전환하여, 미군'위안부'의 역사와 피해자들의 명예를 회복하기 위한 공간으로 활용하고자 설립되었습니다.",
    'about.declarationTitle': '창립 선언문 중',
    'about.declarationQuote': '"사단법인 평화시민행동은 분단의 아픔과 상처를 안고 있는 이 땅에 평화와 인권의 가치를 뿌리내리고, 실천적 시민행동을 통해 자유와 정의가 바로 서는 평화로운 민주사회를 실현합니다."',
    'about.coreValuesTitle': '핵심 가치 & 추진 사업',
    'about.val1Title': '역사 기록 & 보존',
    'about.val1Desc': '잊혀진 미군\'위안부\' 역사를 구술 및 사료로 기록하고 보존합니다.',
    'about.val2Title': '명예 회복',
    'about.val2Desc': '피해자들의 가려진 삶을 드러내어 사회적 명예 회복에 앞장섭니다.',
    'about.val3Title': '의식 전환',
    'about.val3Desc': '시민들과 함께 평화와 인권의 중요성을 배우고 확산합니다.',
    'about.val4Title': '연대와 행동',
    'about.val4Desc': '국내외 평화인권 단체들과 연대하여 실천적 평화운동을 전개합니다.',
    'about.orgChartTitle': '조직 구성 & 대표 인사말',
    'about.quoteTitle': '함께 만드는 평화의 보금자리',
    'about.quoteText': '기억과 평화의 집은 한 분 한 분의 정성 어린 시민 모금으로 건립되며, 누구나 찾아와 안식을 얻고 평화를 논하는 열린 시민 공간이 될 것입니다.',
    'about.repTitle': '사단법인 평화시민행동 대표이사',

    // News
    'news.sectionTag': '소식 및 활동',
    'news.sectionTitle': '기억과 평화의 집 소식',
    'news.sectionSubtitle': '기억과 평화의 집의 생생한 사업 소식과 카드뉴스를 전해드립니다.',
    'news.tabAll': '전체',
    'news.tabNews': '소식',
    'news.tabActivity': '활동',
    'news.tabNotice': '공지',
    'news.tabArchive': '아카이브',
    'news.searchPlaceholder': '소식 검색...',
    'news.watchStream': '방송 시청하기',
    'news.readMore': '자세히 보기',
    'news.close': '닫기',
    'news.views': '조회수',
    'news.likes': '좋아요',
    'news.share': '공유',
    'news.linkCopied': '링크가 복사되었습니다!',

    // Donation & Sponsorship
    'don.sectionTag': '후원 안내',
    'don.sectionTitle': '기억과 평화의 집 후원',
    'don.sectionSubtitle': "윤금이 씨 사건 터를 매입하여 조성하는 '기억과 평화의 집' 건립 및 운영 후원에 함께해 주세요.\n소중한 후원금은 역사를 기록하고 피해자들의 명예를 회복하는 평화 보금자리가 됩니다.",
    'don.tabForm': '후원 신청하기',
    'don.tabBank': '계좌 입금 안내',
    'don.tabWhy': '왜 후원이 필요한가요?',
    'don.tabTax': '세제 혜택 안내',
    'don.tabDonors': '기부자 응원 현황',
    'don.typeOnce': '일시 후원',
    'don.typeMonthly': '정기 후원',
    'don.selectAmount': '후원 금액 선택',
    'don.customAmount': '직접 입력',
    'don.customAmountPlaceholder': '금액 입력 (원)',
    'don.donorName': '기부자 성명 / 단체명',
    'don.phone': '연락처',
    'don.email': '이메일',
    'don.message': '응원의 한마디 (선택)',
    'don.messagePlaceholder': '기억과 평화의 집 건립을 응원하는 따뜻한 한마디를 입력해 주세요.',
    'don.anonymous': '익명 기부로 참여',
    'don.receiptRequest': '기부금 영수증 발급 신청',
    'don.receiptIndiv': '개인 (주민등록번호)',
    'don.receiptCorp': '법인 (사업자등록번호)',
    'don.residentNo': '주민등록번호',
    'don.businessNo': '사업자등록번호',
    'don.paymentMethod': '결제 수단',
    'don.payBank': '무통장 입금',
    'don.payCard': '신용카드',
    'don.termsAgree': '개인정보 수집 및 이용 동의 (필수)',
    'don.btnSubmit': '후원 참여 신청하기',
    'don.bankAccountTitle': '후원 전용 계좌 안내',
    'don.bankName': '농협은행',
    'don.accountNo': '301-0370-9831-21',
    'don.accountHolder': '예금주: 사단법인 평화시민행동',
    'don.copyAccount': '계좌번호 복사',
    'don.accountCopied': '계좌번호가 복사되었습니다.',
    'don.whyTag': '건립 모금의 이유',
    'don.whyTitle': "왜 '기억과 평화의 집' 건립 모금이 필요할까요?",
    'don.whyBadge1': '기억',
    'don.why1Title': '사라져가는 역사적 현장 보존',
    'don.why1Desc': '동두천 보산동 윤금이 씨 사건 터 매입을 통해 잊혀져 가는 역사의 현장을 온전히 지키고 보존합니다.',
    'don.whyBadge2': '인권',
    'don.why2Title': '기지촌 여성 피해자들의 명예 회복',
    'don.why2Desc': "미군'위안부' 피해자들의 가려진 삶과 인권의 역사를 올바르게 기록하고 사회적 명예 회복을 추진합니다.",
    'don.whyBadge3': '평화',
    'don.why3Title': '평화·인권 교육과 연대의 거점',
    'don.why3Desc': '미래세대를 위한 평화·인권 교육 공간이자 시민들이 함께 연대하고 행동하는 거점을 마련합니다.',
    'don.whyNoticePrefix': '시민 한 분 한 분의 정성으로 모인 ',
    'don.whyNoticeAmount': '1억 1,300만 원',
    'don.whyNoticeSuffix': '은 사건 터 매입과 공간 리모델링, 역사 기록물 보존에 전액 투명하게 사용됩니다.',
    'don.liveGoalStatus': '실시간 후원 목표 현황',
    'don.targetAmountLabel': '모금 목표액',
    'don.currentAmountLabel': '현재 모금액',
    'don.donorCountLabel': '함께한 시민 기부자',
    'don.formHeaderTitle': '일시 후원 신청 및 계좌 안내',
    'don.formHeaderSubtitle': '후원 금액과 후원자 정보를 입력하여 마음을 모아주세요.',
    'don.transparentOp': '투명한 후원 운영',
    'don.donorWallTitle': '기억과 평화의 집 기부자 응원 한마디 현황',
    'don.addMessageBtn': '응원 한마디 남기기',
    'don.taxGuideTitle': '지정기부금 단체 및 세제 혜택 안내',
    'don.taxNotice': '사단법인 평화시민행동은 지정기부금 단체 등록을 추진 중입니다. 등록 완료 시 기부금 영수증 발급 및 소득공제/세액공제 혜택이 적용됩니다.',
    'don.taxPoint1': '지정기부금 개인 후원: 소득금액의 30% 한도 내 15%(3,000만원 초과분 30%) 세액공제',
    'don.taxPoint2': '지정기부금 법인 후원: 소득금액의 10% 한도 내 손금산입 혜택',
    'don.modalSuccessTitle': '소중한 후원 참여에 깊이 감사드립니다!',
    'don.modalSuccessDesc': '보내주신 후원금과 따뜻한 마음은 기억과 평화의 집 건립과 평화·인권 활동에 소중히 사용됩니다.',
    'donate.step1Label': '1. 후원 금액 선택 (원)',
    'donate.onceTag': '1회 일시 후원',
    'donate.customAmountPlaceholder': '직접 금액 입력 (원 단위)',
    'donate.unitWon': '원',
    'donate.selectedAmountLabel': '선택된 일시 후원 금액:',
    'donate.step2Label': '2. 후원자 정보 입력',
    'donate.nameLabel': '성명 또는 단체명 *',
    'donate.namePlaceholder': '홍길동',
    'donate.phoneLabel': '연락처 *',
    'donate.phonePlaceholder': '010-0000-0000',
    'donate.emailLabel': '이메일 (기부 영수증 및 소식지 수신용)',
    'donate.receiptCheckbox': '기부금 영수증 발급 신청 (현재 발급 준비중)',
    'donate.receiptTargetLabel': '발급 대상:',
    'donate.individual': '개인',
    'donate.corporate': '법인·단체',
    'donate.residentIdLabel': '주민등록번호 *',
    'donate.residentIdPlaceholder': '000000-0000000',
    'donate.addressLabel': '주소 *',
    'donate.addressPlaceholder': '주소를 입력해 주세요',
    'donate.bizNoLabel': '사업자등록번호 / 고유번호 *',
    'donate.bizNoPlaceholder': '000-00-00000 또는 고유번호',
    'donate.corpAddressLabel': '법인·단체 소재지(주소) *',
    'donate.corpAddressPlaceholder': '법인·단체 소재지 주소를 입력해 주세요',
    'donate.receiptPrivacyNotice': '※ 입력해주신 정보는 국세청 기부금 영수증 발급 및 연말정산 간소화 서비스 등록 용도로만 안전하게 활용됩니다. (현재 발급 시스템 준비 중이며, 연동 완료 후 순차 안내 예정)',
    'donate.anonymousCheckbox': '익명으로 기부 참여하기 (기부자 벽 성명 비공개)',
    'donate.step3Label': '3. 후원자 응원 한마디',
    'donate.wallPublicTag': '기부자 벽 공개',
    'donate.cheerSubtext': '기억과 평화의 집 건립을 응원하는 따뜻한 희망의 메시지를 남겨주세요.',
    'donate.cheerPlaceholder': '예: 분단의 아픔을 치유하고 평화의 미래를 만들어가는 소중한 공간이 되길 마음 다해 응원합니다!',
    'donate.step4Label': '4. 결제 수단 선택',
    'donate.selectedTag': '선택',
    'donate.bankMethodName': '후원 전용 계좌이체 (무통장 입금)',
    'donate.copySuccess': '복사 완료!',
    'donate.copyAccount': '계좌번호 복사',
    'donate.prepTag': '준비 중',
    'donate.cardMethodName': '신용카드 / 간편결제 (MRN 결제 솔루션 도입 예정)',
    'donate.prepNotice': '※ 현재 시스템 연동 준비 중이며, 곧 더 편리한 간편결제 서비스를 제공할 예정입니다.',
    'donate.paymentGuideHeader': '결제 수단 이용 안내',
    'donate.paymentGuideItem1': '현재 사단법인 평화시민행동의 모금은 후원 전용 계좌를 통한 입금만 가능합니다.',
    'donate.paymentGuideItem2': '기부자분들의 편리하고 안전한 결제를 위해 MRN 결제 솔루션(신용카드, 간편결제 등) 도입을 준비 중에 있습니다.',
    'donate.paymentGuideItem3': '기부금 영수증 발급 서비스는 현재 준비 중입니다. 발급 시스템 마련 후 순차적으로 안내해 드릴 예정입니다.',
    'donate.submitBtnSuffix': '일시 후원 참여하기',
    'donate.modalTag': '기억과 평화의 집 후원',
    'donate.modalTitle': '기억과 평화의 집 후원 참여하기',
    'donate.modalSubtitle': '금액을 선택하고 후원자 정보를 입력하여 평화의 보금자리 건립에 동참해 주세요.',
    'donate.liveCheerStatusTag': '실시간 응원 현황',
    'donate.searchPlaceholder': '기부자 이름 또는 응원 검색',
    'donate.noCheerMsg': '아직 등록된 응원 메시지가 없습니다. 첫 번째 응원의 한마디를 남겨주세요!',
    'donate.donorTypeLabel': '일시 후원자',
    'donate.certModalTitle': '기여 증서 & 감사의 글',
    'donate.certModalSubtitle': '소중한 기부에 진심으로 감사드립니다. 귀하의 정성은 기억과 평화의 집 건립을 위해 투명하게 쓰입니다.',
    'donate.certIssuerLabel': '발급기관',
    'donate.certIssuerValue': '사단법인 평화시민행동 (기억과 평화의 집)',
    'donate.certDonorLabel': '기부자',
    'donate.certAmountLabel': '후원 금액',
    'donate.certDateLabel': '후원 일자',
    'donate.certNoLabel': '증서 번호',
    'donate.certDownloadBtn': '증서 다운로드',
    'donate.certConfirmBtn': '확인',
    'donate.errorName': '성명 또는 단체명을 입력해 주세요.',
    'donate.errorPhone': '연락처를 입력해 주세요.',
    'donate.errorAmount': '최소 후원 금액은 1,000원 이상이어야 합니다.',

    // Sponsorship Section
    'spons.sectionTag': '후원 안내 & 혜택',
    'spons.sectionTitle': '지속 가능한 평화를 만드는 후원 안내',
    'spons.sectionSubtitle': '기억과 평화의 집의 모든 후원금은 기부금품법 및 법인 재정 공개 규정에 따라 투명하게 관리됩니다.',
    'spons.card1Tag': '직접 계좌 입금 안내',
    'spons.card1Title': '기억과 평화의 집 후원 전용 계좌',
    'spons.card1Desc': '인터넷뱅킹, 무통장 입금으로 후원에 동참하실 수 있습니다.',
    'spons.bankInfoLabel': '후원 계좌 정보',
    'spons.bankName': '농협은행',
    'spons.accountHolder': '사단법인 평화시민행동',
    'spons.copySuccess': '계좌번호가 복사되었습니다!',
    'spons.copyBtn': '계좌번호 복사하기',
    'spons.card2Tag': '연말정산 기부금 소득공제 혜택',
    'spons.card2Title': '기부금 영수증 발급 세제 혜택 (발급 준비중)',
    'spons.benefit1Title': '지정기부금 단체:',
    'spons.benefit1Desc': '개인 후원 시 소득금액의 30% 한도 내에서 15%(3,000만원 초과분은 30%) 세액공제 혜택이 제공됩니다.',
    'spons.benefit2Title': '법인 후원:',
    'spons.benefit2Desc': '법인 소득금액의 10% 한도 내에서 손금산입(비용 인정) 혜택이 적용됩니다.',
    'spons.benefit3Title': '국세청 연말정산 간소화:',
    'spons.benefit3Desc': '기부금 영수증 발급 서비스는 현재 준비 중입니다.',
    'spons.contactNote': '* 기부금 영수증 발급 문의 (준비중): 전화 031-823-6155 / 이메일 peaceaction6155@gmail.com',

    // Archive
    'arch.sectionTag': '아카이브',
    'arch.sectionTitle': '역사 및 사료 아카이브',
    'arch.sectionSubtitle': '기억과 평화의 집 역사 기록 및 구술 자료 모음',
    'arch.filterAll': '전체',
    'arch.filterMedia': '사진/영상',
    'arch.filterDoc': '사료/기록',
    'arch.tagSearch': '태그 검색...',
    'arch.viewDetail': '자료 보기',
    'archive.tag': '디지털 기록관',
    'archive.title': '기억과 평화 아카이브',
    'archive.subtitle': '기억과 평화의 집 역사 기록 및 구술 자료 모음',
    'archive.statusBadge': '자료 정리 중',
    'archive.statusTitle': '아카이브는 현재 준비중입니다.',
    'archive.statusDesc': '역사 자료 및 구술 기록을 더욱 정갈하게 정리하여 정식 순차 공개할 예정입니다.',

    // Articles Accordion
    'art.title': '사단법인 평화시민행동 정관 목적 및 사업 원문',
    'art.header': '제2조(목적) 및 제3조(사업)',
    'art.art2Title': '제2조(목적)',
    'art.art2Content': '본 법인은 한반도 분단과 그로 인한 아픔의 상처가 존속하고 있는 우리나라에 평화와 인권의식을 높이고 기억과 평화의 공간을 마련하고 실천적인 시민행동을 통하여 자유와 정의, 인권이 바르게 실현되는 평화로운 민주사회를 이루기 위함을 목적으로 한다.',
    'art.art3Title': '제3조(사업)',
    'art.art3Item1': '1. 교육사업',
    'art.art3Item2': '2. ‘기억과 평화의 집’ 건립 및 운영사업',
    'art.art3Item3': '3. 기지촌여성 지원사업',
    'art.art3Item4': '4. 공익활동지원사업',
    'art.art3Item5': '5. 정책 제안 및 입법활동',
    'art.art3Item6': '6. 국내 및 국제 교류사업',
    'art.art3Item7': '7. 연구, 학술, 출판사업',
    'art.art3Item8': '8. 공공부문 민간 위탁사업',
    'art.art3Item9': '9. 기타 본 법인의 목적달성에 필요한 사업',

    // Footer
    'footer.orgName': '사단법인평화시민행동',
    'footer.subOrgName': 'Peace Citizens Action Inc.',
    'footer.tagline': '기억과 평화의 집은 역사의 소중한 기록을 수집·보존하고, 미래 세대를 위한 평화 문화 형성 및 인권 증진을 실천하고 행동하는 사단법인입니다.',
    'footer.desc': '기억과 평화의 집은 역사의 소중한 기록을 수집·보존하고, 미래 세대를 위한 평화 문화 형성 및 인권 증진을 실천하고 행동하는 사단법인입니다.',
    'footer.trustBadge': '지정기부금 단체 등록 추진 준비 중',
    'footer.taxBadge': '지정기부금 단체 등록 추진 준비 중',
    'footer.quickNav': '주요 메뉴',
    'footer.contactInfo': '법인 정보 및 문의',
    'footer.regTitle': '법인 및 사업자 등록 정보',
    'footer.repLabel': '대표이사:',
    'footer.repValue': '김대용',
    'footer.bizNoLabel': '고유번호:',
    'footer.phoneLabel': '전화:',
    'footer.faxLabel': '팩스:',
    'footer.emailLabel': '이메일:',
    'footer.addressLabel': '주소:',
    'footer.address': '11330 경기도 동두천시 어수로 101번길 35. 3층',
    'footer.backToTop': '맨 위로 이동',
    'footer.rep': '대표자: 김대용',
    'footer.email': '이메일: peaceaction6155@gmail.com',
    'footer.copyright': '© 2026 기억과 평화의 집 (House of Memory & Peace). All rights reserved.',
  },
  en: {
    // Header
    'header.orgName': 'Peace Citizens Action Inc.',
    'header.subOrgName': 'Non-Profit Organization',
    'nav.about': 'About',
    'nav.news': 'News & Activities',
    'nav.sponsorship': 'Support House of Peace',
    'nav.archive': 'Archive',
    'header.donateBtn': 'Support House of Peace',
    'header.mobileDonateBtn': 'Join Donation Campaign',

    // Hero
    'hero.badge': 'Yun Geum-i Incident Site Citizen Asset Project / Peace & Memory',
    'hero.titleLine1': 'Transforming the 1992 Yun Geum-i Incident Site',
    'hero.titleLine2': 'Into a House of Memory & Peace',
    'hero.description': "Through citizen action, we acquire the site of the painful 1992 Yun Geum-i incident in Bosan-dong, Dongducheon. We document the hidden history of US military 'comfort women', restore the victims' dignity, and build a sanctuary of peace and human rights for future generations.",
    'hero.btnDonate': 'Donate to House of Memory & Peace',
    'hero.btnNews': 'View News & Activities',
    'hero.trustBadge1': 'Preparing Registration as Designated Donation Charity',
    'hero.trustBadge2': 'Transparent Financial Disclosure',
    'hero.campaignBadge': 'Building & Operation Campaign',
    'hero.campaignTitle': 'House of Memory & Peace Fund',
    'hero.campaignRate': 'Goal Reached',
    'hero.currentAmountLabel': 'Current Raised:',
    'hero.targetAmountLabel': 'Target:',
    'hero.donorsLabel': 'Citizen Donors',
    'hero.cheersLabel': 'Encouragement Messages',
    'hero.unitPeople': '',
    'hero.unitCount': '',
    'hero.btnDonateCard': 'Join Fundraising Now',

    // About
    'about.sectionTag': 'ABOUT US',
    'about.sectionTitle': 'About Peace Citizens Action Inc.',
    'about.sectionSubtitle': 'Peace Citizens Action Inc. realizes peace and human rights values through practical action to heal the wounds of national division.',
    'about.headingTitle': 'Cultivating a Future of Peace Through Memory',
    'about.foundingDate': 'Founded on April 27, 2026',
    'about.declarationHeader': 'Deeply Rooting the Values of Peace and Human Rights',
    'about.cardTitle': 'A Space for Peace & Human Rights Built by Citizens',
    'about.cardText': "Peace Citizens Action Inc. was established on April 27, 2026. It was founded to acquire the site of the Yun Geum-i incident through citizen contributions and transform it into the 'House of Memory & Peace', dedicated to recording the history of US military 'comfort women' and restoring the dignity of victims.",
    'about.declarationTitle': 'From the Founding Declaration',
    'about.declarationQuote': '"Peace Citizens Action Inc. roots the values of peace and human rights in this land bearing the pain of division, and realizes a peaceful democratic society where freedom and justice stand firm through active citizen engagement."',
    'about.coreValuesTitle': 'Core Values & Key Projects',
    'about.val1Title': 'History & Preservation',
    'about.val1Desc': 'Documenting and preserving the hidden history of US military "comfort women" through oral testimonies and historical records.',
    'about.val2Title': 'Restoring Dignity',
    'about.val2Desc': 'Bringing light to victims\' concealed lives and leading efforts to restore their social honor and dignity.',
    'about.val3Title': 'Awareness & Education',
    'about.val3Desc': 'Fostering and spreading peace and human rights education together with citizens.',
    'about.val4Title': 'Solidarity & Action',
    'about.val4Desc': 'Engaging in practical peace movements in solidarity with domestic and international human rights organizations.',
    'about.orgChartTitle': 'Organization & Representative Message',
    'about.quoteTitle': 'Building a Sanctuary of Peace Together',
    'about.quoteText': 'The House of Memory & Peace is established through the heartfelt donations of individual citizens, serving as an open sanctuary for anyone to find rest and converse about peace.',
    'about.repTitle': 'Representative Director, Peace Citizens Action Inc.',

    // News
    'news.sectionTag': 'NEWS & ACTIVITIES',
    'news.sectionTitle': 'House of Memory & Peace News',
    'news.sectionSubtitle': 'Stay updated with the latest news, updates, and card news from the House of Memory & Peace.',
    'news.tabAll': 'All',
    'news.tabNews': 'News',
    'news.tabActivity': 'Activities',
    'news.tabNotice': 'Notices',
    'news.tabArchive': 'Archive',
    'news.searchPlaceholder': 'Search news...',
    'news.watchStream': 'Watch Broadcast',
    'news.readMore': 'Read More',
    'news.close': 'Close',
    'news.views': 'Views',
    'news.likes': 'Likes',
    'news.share': 'Share',
    'news.linkCopied': 'Link copied to clipboard!',

    // Donation & Sponsorship
    'don.sectionTag': 'DONATION GUIDE',
    'don.sectionTitle': 'Support House of Memory & Peace',
    'don.sectionSubtitle': "Join us in supporting the purchase and operation of the 'House of Memory & Peace' on the Yun Geum-i incident site. Your generous donations preserve history and build a sanctuary to restore victims' dignity.",
    'don.tabForm': 'Donation Form',
    'don.tabBank': 'Bank Transfer Info',
    'don.tabWhy': 'Why Donate?',
    'don.tabTax': 'Tax Benefits',
    'don.tabDonors': 'Donor Wall',
    'don.typeOnce': 'One-Time Donation',
    'don.typeMonthly': 'Monthly Donation',
    'don.selectAmount': 'Select Amount',
    'don.customAmount': 'Custom Amount',
    'don.customAmountPlaceholder': 'Enter amount (KRW)',
    'don.donorName': 'Donor Name / Organization',
    'don.phone': 'Phone Number',
    'don.email': 'Email Address',
    'don.message': 'Encouragement Message (Optional)',
    'don.messagePlaceholder': 'Leave a warm message of support for building the House of Memory & Peace.',
    'don.anonymous': 'Donate Anonymously',
    'don.receiptRequest': 'Request Tax Receipt',
    'don.receiptIndiv': 'Individual (Resident Reg. No.)',
    'don.receiptCorp': 'Corporate (Business Reg. No.)',
    'don.residentNo': 'Resident Registration Number',
    'don.businessNo': 'Business Registration Number',
    'don.paymentMethod': 'Payment Method',
    'don.payBank': 'Direct Bank Transfer',
    'don.payCard': 'Credit Card',
    'don.termsAgree': 'Agree to Personal Information Collection (Required)',
    'don.btnSubmit': 'Submit Donation',
    'don.bankAccountTitle': 'Donation Bank Account Details',
    'don.bankName': 'NongHyup Bank (NH Bank)',
    'don.accountNo': '301-0370-9831-21',
    'don.accountHolder': 'Account Holder: Peace Citizens Action Inc.',
    'don.copyAccount': 'Copy Account Number',
    'don.accountCopied': 'Account number copied to clipboard.',
    'don.whyTag': 'Reason for Construction Fundraising',
    'don.whyTitle': "Why Is Fundraising Needed for the 'House of Memory & Peace'?",
    'don.whyBadge1': 'Memory',
    'don.why1Title': 'Preserving Disappearing Historical Sites',
    'don.why1Desc': 'Protecting and preserving the forgotten historical site through the acquisition of the Yun Geum-i incident site in Bosan-dong, Dongducheon.',
    'don.whyBadge2': 'Human Rights',
    'don.why2Title': 'Restoring the Honor of Victims in Military Camp Towns',
    'don.why2Desc': 'Accurately documenting the hidden lives and human rights history of US military "comfort women" victims and restoring their social dignity.',
    'don.whyBadge3': 'Peace',
    'don.why3Title': 'A Hub for Peace & Human Rights Education and Solidarity',
    'don.why3Desc': 'Creating an educational space for peace and human rights for future generations, and a hub where citizens unite and take action.',
    'don.whyNoticePrefix': 'The ',
    'don.whyNoticeAmount': '113 Million KRW',
    'don.whyNoticeSuffix': ' gathered through individual citizen donations will be transparently used in full for site acquisition, space remodeling, and historical archive preservation.',
    'don.liveGoalStatus': 'Live Fundraising Goal Status',
    'don.targetAmountLabel': 'Fundraising Goal',
    'don.currentAmountLabel': 'Current Amount Raised',
    'don.donorCountLabel': 'Participating Donors',
    'don.formHeaderTitle': 'One-Time Donation & Bank Transfer Info',
    'don.formHeaderSubtitle': 'Please enter your donation amount and donor details to join us.',
    'don.transparentOp': 'Transparent Operation',
    'don.donorWallTitle': 'House of Memory & Peace Donor Wall',
    'don.addMessageBtn': 'Leave a Message',
    'don.taxGuideTitle': 'Tax Deductions & Charity Status',
    'don.taxNotice': 'Peace Citizens Action Inc. is applying for Designated Donation Charity status. Tax receipts and deductions will be applicable upon approval.',
    'don.taxPoint1': 'Individual Donations: Up to 15% tax credit (30% for over 30M KRW) within 30% of income.',
    'don.taxPoint2': 'Corporate Donations: Tax deductible up to 10% of taxable income.',
    'don.modalSuccessTitle': 'Thank you for your generous support!',
    'don.modalSuccessDesc': 'Your donation and heartfelt encouragement will be dedicated to constructing and operating the House of Memory & Peace.',
    'donate.step1Label': '1. Select Donation Amount (KRW)',
    'donate.onceTag': 'One-Time Donation',
    'donate.customAmountPlaceholder': 'Enter custom amount (KRW)',
    'donate.unitWon': 'KRW',
    'donate.selectedAmountLabel': 'Selected One-Time Amount:',
    'donate.step2Label': '2. Donor Information',
    'donate.nameLabel': 'Name or Organization *',
    'donate.namePlaceholder': 'John Doe',
    'donate.phoneLabel': 'Phone Number *',
    'donate.phonePlaceholder': '010-0000-0000',
    'donate.emailLabel': 'Email (for receipts & newsletters)',
    'donate.receiptCheckbox': 'Request Donation Receipt (Currently in Prep)',
    'donate.receiptTargetLabel': 'Target:',
    'donate.individual': 'Individual',
    'donate.corporate': 'Corporate / Org',
    'donate.residentIdLabel': 'Resident Registration No. *',
    'donate.residentIdPlaceholder': '000000-0000000',
    'donate.addressLabel': 'Address *',
    'donate.addressPlaceholder': 'Please enter your address',
    'donate.bizNoLabel': 'Business Registration / Tax ID *',
    'donate.bizNoPlaceholder': '000-00-00000 or Tax ID',
    'donate.corpAddressLabel': 'Corporate Address *',
    'donate.corpAddressPlaceholder': 'Enter corporate address',
    'donate.receiptPrivacyNotice': '※ Information provided is strictly used for NTS tax receipts. (System under preparation)',
    'donate.anonymousCheckbox': 'Donate Anonymously (Hide name on donor wall)',
    'donate.step3Label': '3. Message of Encouragement',
    'donate.wallPublicTag': 'Public on Wall',
    'donate.cheerSubtext': 'Leave a message of hope supporting the House of Memory & Peace.',
    'donate.cheerPlaceholder': 'e.g., Wishing for a sanctuary of peace and human rights!',
    'donate.step4Label': '4. Select Payment Method',
    'donate.selectedTag': 'Selected',
    'donate.bankMethodName': 'Direct Bank Transfer',
    'donate.copySuccess': 'Copied!',
    'donate.copyAccount': 'Copy Account',
    'donate.prepTag': 'In Preparation',
    'donate.cardMethodName': 'Credit Card / Easy Pay (Coming Soon)',
    'donate.prepNotice': '※ Payment gateway solutions are under integration for convenience.',
    'donate.paymentGuideHeader': 'Payment Method Notice',
    'donate.paymentGuideItem1': 'Donations are currently processed through direct bank transfer.',
    'donate.paymentGuideItem2': 'Credit card and easy payment solutions (MRN) will be available soon.',
    'donate.paymentGuideItem3': 'Tax receipt services will be announced after system integration.',
    'donate.submitBtnSuffix': 'Join One-Time Donation',
    'donate.modalTag': 'House of Memory & Peace Donation',
    'donate.modalTitle': 'Support House of Memory & Peace',
    'donate.modalSubtitle': 'Select an amount and enter donor details to help build a sanctuary of peace.',
    'donate.liveCheerStatusTag': 'Live Encouragement Wall',
    'donate.searchPlaceholder': 'Search donor name or message',
    'donate.noCheerMsg': 'No messages yet. Be the first to leave a message of encouragement!',
    'donate.donorTypeLabel': 'One-Time Donor',
    'donate.certModalTitle': 'Certificate of Appreciation & Thanks',
    'donate.certModalSubtitle': 'Thank you deeply for your donation. Your support transparently empowers the House of Memory & Peace.',
    'donate.certIssuerLabel': 'Issuer',
    'donate.certIssuerValue': 'Peace Citizens Action Inc. (House of Memory & Peace)',
    'donate.certDonorLabel': 'Donor',
    'donate.certAmountLabel': 'Donation Amount',
    'donate.certDateLabel': 'Donation Date',
    'donate.certNoLabel': 'Certificate No.',
    'donate.certDownloadBtn': 'Download Certificate',
    'donate.certConfirmBtn': 'Confirm',
    'donate.errorName': 'Please enter your name or organization name.',
    'donate.errorPhone': 'Please enter your phone number.',
    'donate.errorAmount': 'Minimum donation amount is 1,000 KRW.',

    // Sponsorship Section
    'spons.sectionTag': 'Sponsorship & Benefits',
    'spons.sectionTitle': 'Sponsorship Guide for Sustainable Peace',
    'spons.sectionSubtitle': 'All donations for the House of Memory & Peace are transparently managed under donation laws and public financial reporting guidelines.',
    'spons.card1Tag': 'Direct Bank Transfer Info',
    'spons.card1Title': 'House of Memory & Peace Donation Account',
    'spons.card1Desc': 'You can participate in fundraising through direct wire transfer or online banking.',
    'spons.bankInfoLabel': 'Donation Account Details',
    'spons.bankName': 'NongHyup Bank (NH Bank)',
    'spons.accountHolder': 'Peace Citizens Action Inc.',
    'spons.copySuccess': 'Account number copied!',
    'spons.copyBtn': 'Copy Account Number',
    'spons.card2Tag': 'Year-End Tax Deduction Benefits',
    'spons.card2Title': 'Donation Receipt & Tax Benefit Notice (In Preparation)',
    'spons.benefit1Title': 'Designated Charity:',
    'spons.benefit1Desc': 'Individual donors receive up to 15% tax credit (30% for amounts exceeding 30M KRW) within 30% of income.',
    'spons.benefit2Title': 'Corporate Sponsorship:',
    'spons.benefit2Desc': 'Deductible as corporate expenses up to 10% of taxable corporate income.',
    'spons.benefit3Title': 'NTS Tax Simplification:',
    'spons.benefit3Desc': 'Donation receipt service is currently under preparation.',
    'spons.contactNote': '* Receipt inquiries (in prep): Phone +82-31-823-6155 / Email peaceaction6155@gmail.com',

    // Archive
    'arch.sectionTag': 'ARCHIVE',
    'arch.sectionTitle': 'History & Archives',
    'arch.sectionSubtitle': 'Collection of historical records, photos, and testimonies for the House of Memory & Peace',
    'arch.filterAll': 'All',
    'arch.filterMedia': 'Photos & Videos',
    'arch.filterDoc': 'Historical Documents',
    'arch.tagSearch': 'Search tags...',
    'arch.viewDetail': 'View Item',
    'archive.tag': 'Digital Archive',
    'archive.title': 'Memory & Peace Archive',
    'archive.subtitle': 'Collection of historical records and oral histories',
    'archive.statusBadge': 'Organizing Materials',
    'archive.statusTitle': 'Archive is currently under preparation.',
    'archive.statusDesc': 'Historical materials and testimonies are being cataloged and will be released sequentially.',

    // Articles Accordion
    'art.title': 'Articles of Association: Purpose & Operations',
    'art.header': 'Article 2 (Purpose) & Article 3 (Operations)',
    'art.art2Title': 'Article 2 (Purpose)',
    'art.art2Content': 'This corporation aims to heighten peace and human rights awareness in South Korea—a land bearing the ongoing pain of division—by establishing spaces of memory and peace, and through practical citizen action, realizing a peaceful democratic society where freedom, justice, and human rights are fully upheld.',
    'art.art3Title': 'Article 3 (Operations)',
    'art.art3Item1': '1. Educational programs',
    'art.art3Item2': '2. Establishment and operation of the "House of Memory & Peace"',
    'art.art3Item3': '3. Support programs for women in camp towns (Gijichon)',
    'art.art3Item4': '4. Public interest activity support',
    'art.art3Item5': '5. Policy proposals and legislative advocacy',
    'art.art3Item6': '6. Domestic and international exchange projects',
    'art.art3Item7': '7. Research, academic studies, and publishing',
    'art.art3Item8': '8. Public sector civil commissioned projects',
    'art.art3Item9': '9. Other operations necessary to achieve the corporation\'s purpose',

    // Footer
    'footer.orgName': 'Peace Citizens Action Inc.',
    'footer.subOrgName': 'Non-Profit Organization',
    'footer.tagline': 'House of Memory & Peace is a non-profit organization dedicated to collecting and preserving historic records, promoting a culture of peace for future generations, and advancing human rights.',
    'footer.desc': 'House of Memory & Peace is a non-profit organization dedicated to collecting and preserving historic records, promoting a culture of peace for future generations, and advancing human rights.',
    'footer.trustBadge': 'Preparing Registration as Designated Donation Charity',
    'footer.taxBadge': 'Preparing Registration as Designated Donation Charity',
    'footer.quickNav': 'Navigation',
    'footer.contactInfo': 'Organization Info & Contact',
    'footer.regTitle': 'Registration & Contact Information',
    'footer.repLabel': 'Representative:',
    'footer.repValue': 'Dae-yong Kim',
    'footer.bizNoLabel': 'Tax ID / Org No:',
    'footer.phoneLabel': 'Phone:',
    'footer.faxLabel': 'Fax:',
    'footer.emailLabel': 'Email:',
    'footer.addressLabel': 'Address:',
    'footer.address': '3F, 35 Eosuro 101beon-gil, Dongducheon-si, Gyeonggi-do, 11330, Rep. of Korea',
    'footer.backToTop': 'Back to Top',
    'footer.rep': 'Representative: Dae-yong Kim',
    'footer.email': 'Email: peaceaction6155@gmail.com',
    'footer.copyright': '© 2026 House of Memory & Peace. All rights reserved.',
  },
};
